- name: Save Docker image
  run: docker save -o app.tar muqadam99/ci-cd-node-app:latest

- name: Copy image to EC2
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    source: "app.tar"
    target: "~/"

- name: Load and run image on EC2
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    script: |
      docker load -i ~/app.tar
      docker stop app || true
      docker rm app || true
      docker run -d -p 80:3000 --name app muqadam99/ci-cd-node-app:latest
