name: Build, Push, and Test Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: muqadam99/ci-cd-node-app:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull the pushed Docker image
        run: docker pull muqadam99/ci-cd-node-app:latest

      - name: Run the Docker container and test the app
        run: |
          docker run -d -p 3000:3000 --name app muqadam99/ci-cd-node-app:latest
          sleep 5
          docker logs app
          curl -f http://localhost:3000
          docker stop app
          docker rm app
